version: '3'
services:
  app:
    container_name: tourmaline-backend
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/app 
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: uvicorn server:app --host 0.0.0.0 --port 8000 --reload
